#! /bin/bash
	
# This line parses the template and put the result in studentcode.py
parsetemplate --output student/studentcode.py template.py 

# Verify the output of the code...
output=$(run_student python student/studentcode.py)
if [ "$output" = "Hello World!" ]; then
	# The student succeeded
	feedback --result success --feedback "You solved this *difficult* task!"
else
	# The student failed
	feedback --result failed --feedback "Your output is $output"
fi