#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2014-2015 Université Catholique de Louvain.
#
# This file is part of INGInious.
#
# INGInious is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# INGInious is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with INGInious.  If not, see <http://www.gnu.org/licenses/>.
"""
    Small tool to allow verification of .task and .course files.
    Usage:
        checktask course_id/task_id
"""
import sys

import common.base
import webapp
from webapp.custom.courses import FrontendCourse
from webapp.custom.tasks import FrontendTask
def usage():
    """ Usage """
    print "Usage: checktask course_id/task_id"
    exit(1)

if not len(sys.argv) == 2:
    usage()

# Read input argument
ids = sys.argv[1].split('/')
courseid = ids[0]
taskid = ids[1]

# Change default path to task Directory
webapp.configuration.INGIniousConfiguration.load("./configuration.json")
taskdir = webapp.configuration.INGIniousConfiguration['tasks_directory'] + '/' + courseid + '/' + taskid

# HTML Tidy
webapp.configuration.INGIniousConfiguration["allow_html"] = "tidy"

try:
    FrontendTask(FrontendCourse(courseid), taskid)
except Exception as inst:
    print "There was an error while validating the file:"
    print inst
    exit(1)
else:
    print "File verification succeeded"
    exit(0)
