# Backend
# Can be:
# - "local" (run containers on the same machine)
# - or an address to a distant manually-launched backend, in the form "tcp://host.be:3000", "udp://host.be:3000" or "ipc:///path/to/socket"
backend: local

# Logging level
log_level: INFO

# Display errors? Possible values:
# - false : do not display the error outside the log
# - true : display the error directly in the browser. useful when debugging locally, but dangerous in production,
#         as it may expose passwords and other sensitive data
# - "your@email.com": send error report to the indicated email
web_debug: false

# Only for backend: local
local-config:
    # debug_host: localhost  # host that will be indicated to users when they want to use the task remote debug feature. Automatically guessed by
                             # default
    debug_ports: 64000-64100 #port range use for remote debug feature

# MongoDB options
mongo_opt:
    host: localhost
    database: INGInious

# Location of the task directory
tasks_directory: ./inginious/tasks

# Use single minified javascript file (production) or multiple files (dev) ?
use_minified_js: true

# URL of a node app INGInious-xterm, properly configured, that allows to run in-browser ssh debug
# If you don't want to install/activate it, just set it to None or remove it from the file
webterm: "https://my-host.be:8080"

# Location of the backup directory (webapp)
backup_directory: ./inginious/backup

# Plugins that will be loaded by the webapp
plugins:
  - plugin_module: inginious.frontend.plugins.auth.demo_auth
    users:
        # register the user "test" with the password "test"
        test: test

# Superadmins: list of user names that are administrators on all courses
superadmins:
  - test

# Disable INGInious?
maintenance: false

# Email info
smtp:
    sendername: 'INGInious <no-reply@inginious.org>'
    host: 'smtp.gmail.com'
    port: 587
    username: 'configme@gmail.com'
    password: 'secret'
    starttls: True

#reverse proxy fix
reverse-proxy-config:
    enable: false
    x_for: 1
    x_host: 1
