#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# This file is part of INGInious. See the LICENSE and the COPYRIGHTS files for
# more information about the licensing of this file.
#

""" Starts the lti frontend """

import os
import argparse
from inginious.common.base import load_json_or_yaml

import inginious.frontend.lti.app
from inginious.frontend.lti.installer import Installer

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", help="Path to configuration file. By default: configuration.yaml or configuration.json")
    parser.add_argument("--host", help="Host to bind to", default="localhost")
    parser.add_argument("--port", help="Port to listen to", type=int, default=8080)
    args = parser.parse_args()

    config = None
    if args.config is None:
        if os.path.isfile("./configuration.lti.yaml"):
            config = "./configuration.lti.yaml"
        elif os.path.isfile("./configuration.lti.json"):
            config = "./configuration.lti.json"
        else:
            raise Exception("No configuration file found. Please check that the file configuration.lti.yaml exists.")
    else:
        config = args.config
    inginious.frontend.lti.app.start_app(load_json_or_yaml(config), hostname=args.host, port=args.port)
