#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2014-2015 Université Catholique de Louvain.
#
# This file is part of INGInious.
#
# INGInious is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# INGInious is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with INGInious.  If not, see <http://www.gnu.org/licenses/>.
""" Creates configuration file for the various frontends """

import argparse
import inginious.frontend.lti.installer
import inginious.frontend.webapp.installer

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Creates a configuration file for the specified frontend.')
    parser.add_argument("--file", help="Path to configuration file. If not set, use the default for the given frontend.")
    parser.add_argument("frontend", choices=['lti', 'webapp'], help="Frontend to configure")
    args = parser.parse_args()

    if args.frontend == "lti":
        inginious.frontend.lti.installer.Installer(args.file).run()
    elif args.frontend == "webapp":
        inginious.frontend.webapp.installer.Installer(args.file).run()