#!/bin/bash

#Get code input and performs dos2unix
getinput thecode | tr -d '\r' > thecode

#Execute the code
chmod +x thecode
./thecode
ERROR_CODE=$?

if [ -f /.__output/generated.txt ]; then
    feedback-result success
    feedback-msg -m "OK. Now go and download your submission files in the administration pages and check for the file."
    feedback-grade 100
elif [ $ERROR_CODE -eq 0 ]; then
	feedback-result failed
    feedback-msg -m "It seems the file cannot not be found. Did you use the \`\`archive\`\` API correctly ?"
    feedback-grade 0
else
	feedback-result failed
    feedback-msg -m "The script you wrote just failed to run :-( Did you generated the \`\`generated.txt\`\` file ?"
    feedback-grade 0
fi
